### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ManoaNosea** [minyuanye/SIUN#3]
Runtime total @iter 2:4.384
Traceback (most recent call last):
  File "deblur.py", line 53, in <module>
    Application(config).start()
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\SIUN-master\code\src\application.py", line 23, in start
    self.application()
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\SIUN-master\code\src\application.py", line 116, in application
    io.imsave(os.path.join(self.config.application.deblurring_result_dir, 'deblur'+str(iter)+'_'+infos[1]))
IndexError: list index out of range

**Comment by ManoaNosea** [comment]
```
-- infos = fileFullPath.rsplit('/', 1)
++ infos = os.path.basename(fileFullPath)
-- io.imsave(os.path.join(self.config.application.deblurring_result_dir, 'deblur'+str(iter)+'_'+infos[1]),deblur)
++ io.imsave(os.path.join(self.config.application.deblurring_result_dir, 'deblur'+str(iter)+'_'+infos),deblur)
```

**Comment by ManoaNosea** [comment]
the user already gives a path, you don't need to do it again

**Comment by minyuanye** [comment]
Yes, your code is more reasonable. The separator char is different on Unix systems ('/') and Windows ('\').
